site_name: Agent Zero Documentation
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
    
  plugins:
    - search
    - search.suggest
    - search.highlight
    - search.share

  markdown_extensions:

    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences