site_name: Agent Zero Documentation
site_description: Welcome to the official documentation for Agent Zero.
site_url: https://3clyp50.github.io/agent-zero
repo_url: https://github.com/frdel/agent-zero
repo_name: frdel/agent-zero
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Installation: installation.md
  - Usage: usage.md
  - Architecture: architecture.md 
  - Contributing: contribution.md  
  - Troubleshooting & FAQ: troubleshooting.md
theme:
  name: material
  language: en 
  icon:
    repo: fontawesome/brands/github 

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Rubik
    code: Roboto Mono
  logo: res/lightSymbol.svg
  favicon: res/darkSymbol.svg
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
    - toc.integrate
    - toc.follow
    - content.code.copy

  plugins:
    - search
    - search.suggest
    - search.highlight
    - search.share
    - offline

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list
    - def_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  extra:
    generator: false