site_name: Agent Zero Documentation
theme:
  name: material
  nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Installation: installation.md
    - Usage: usage.md
    - Architecture: architecture.md
    - Contributing: contribution.md
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Rubik
    code: Roboto Mono
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy

  plugins:
    - search
    - search.suggest
    - search.highlight
    - search.share

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.keys
    - pymdownx.tabbed